#ifndef _KERN_INCLUDE_CONFIG_LOGGER_H_
#define _KERN_INCLUDE_CONFIG_LOGGER_H_

#include "video.h"

#define LOGGER_VIDEO VIDEO_DISPLAY
#define LOGGER_SERIAL VIDEO_SERIAL

#endif /* !_KERN_INCLUDE_CONFIG_LOGGER_H_ */
